swagger: "2.0"
info: 
  version: "0.0.1"
  title: "project demo"
  description: "A simple service to get data from a cloud storage service"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: {}
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths:
  /data/output/<output>:
    get:
      tags:
        - DATA
      operationId: data.download
      description: "Downloads data from url"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Data info"
          schema: {} 
            