swagger: "2.0"
info:
   version: "0.0.1"
   title: "project demo"
   description: "A simple service to get data from a cloud storage service"
   termsOfService: "http://swagger.io/terms/"
   contact:
      name: "Cloudmesh REST Service Example with AI"
   license:
      name: "Apache"
host: "localhost:8080"
basePath: "/project19"
schemes:
   - "http"
consumes:
   - "application/json"
produces:
   - "application/json"
paths:
   /data/output/<output>:
      get:
         operationId: data.download //calls download() from data.py
	 description: "Downloads data from url"
	 produces:
	    - "application/json"
	 responses:
	    "200":
	       description: "Data info"
	       schema:
